# Generated by Django 4.1 on 2022-10-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoryinventory",
            options={"verbose_name_plural": "category"},
        ),
    ]
